### PR TITLE
Added Ruby version

### PR DESCRIPTION
**Pull request by mackuba**

### CODE REVIEW

**Comment by DavidBuchanan314** [comment]
Nice, what kind of speeds are you getting?

**Comment by DavidBuchanan314** [comment]
And, it's been such a long time since I last rubied, can you tl;dr how to install the deps and run it?

**Comment by mackuba** [comment]
Similar times to cbrrr: https://bsky.app/profile/mackuba.eu/post/3ldc3h4ebv22v

For the torture test it's different because the subprocess adds a lot of overhead - if I run it inline then it gets a similar time as the ruby one.

To run, install deps with `bundle` and run with `ruby ruby/bench.rb` or just `ruby/bench.rb`.

**Comment by DavidBuchanan314** [comment]
Thanks!

results on my machine, ruby 3.3.6:

```
Hello World Decode:
===================
cbor-ruby : 326 ns 

Hello World Encode:
===================
cbor-ruby : 219 ns 

Realistic Decode Tests:
=======================
canada.json                    cbor-ruby : 4.10 ms (245.68 MB/s)
citm_catalog.json              cbor-ruby : 3.75 ms (87.10 MB/s)
twitter.json                   cbor-ruby : 2.07 ms (185.74 MB/s)

Realistic Encode Tests:
=======================
canada.json                    cbor-ruby : 1.30 ms (774.84 MB/s)
citm_catalog.json              cbor-ruby : 0.66 ms (497.33 MB/s)
twitter.json                   cbor-ruby : 0.26 ms (1481.53 MB/s)

Decode Torture Tests:
=====================
torture_cids                   cbor-ruby : 26.07 ms (149.96 MB/s)
torture_nested_lists           cbor-ruby : #<CBOR::StackError: stack level too deep>
torture_nested_maps            cbor-ruby : #<CBOR::StackError: stack level too deep>
```

(will add to README soon)

**Pull request merged**
